# Generated by Django 4.2.19 on 2025-04-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomevendorform',
            options={'verbose_name_plural': 'Vendor Applications'},
        ),
    ]
