# Generated by Django 4.2.19 on 2025-04-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('processing', 'Processing')], default='processing', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='used', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('inReview', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.CharField(default='todays date', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Fahrenheit 451', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (1, '★☆☆☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (2, '★★☆☆☆')], default=None),
        ),
    ]
